from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(400, 300)
        self.formLayoutWidget = QtWidgets.QWidget(parent=AddEditCoffeeForm)
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labelName = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.labelName.setObjectName("labelName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelName)
        self.nameEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nameEdit)
        self.labelRoast = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.labelRoast.setObjectName("labelRoast")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelRoast)
        self.roastEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.roastEdit.setObjectName("roastEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.roastEdit)
        self.labelForm = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.labelForm.setObjectName("labelForm")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelForm)
        self.formEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.formEdit.setObjectName("formEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.formEdit)
        self.labelTaste = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.labelTaste.setObjectName("labelTaste")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelTaste)
        self.tasteEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.tasteEdit.setObjectName("tasteEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tasteEdit)
        self.labelPrice = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.labelPrice.setObjectName("labelPrice")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelPrice)
        self.priceEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.priceEdit.setObjectName("priceEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.priceEdit)
        self.labelVolume = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.labelVolume.setObjectName("labelVolume")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelVolume)
        self.volumeEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.volumeEdit.setObjectName("volumeEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.volumeEdit)
        self.saveButton = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.saveButton.setObjectName("saveButton")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cancelButton)

        self.retranslateUi(AddEditCoffeeForm)
        QtCore.QMetaObject.connectSlotsByName(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditCoffeeForm.setWindowTitle(_translate("AddEditCoffeeForm", "Добавить/Редактировать кофе"))
        self.labelName.setText(_translate("AddEditCoffeeForm", "Название:"))
        self.labelRoast.setText(_translate("AddEditCoffeeForm", "Степень обжарки:"))
        self.labelForm.setText(_translate("AddEditCoffeeForm", "Форма:"))
        self.labelTaste.setText(_translate("AddEditCoffeeForm", "Описание вкуса:"))
        self.labelPrice.setText(_translate("AddEditCoffeeForm", "Цена:"))
        self.labelVolume.setText(_translate("AddEditCoffeeForm", "Объём упаковки:"))
        self.saveButton.setText(_translate("AddEditCoffeeForm", "Сохранить"))
        self.cancelButton.setText(_translate("AddEditCoffeeForm", "Отмена"))
