from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CoffeeApp(object):
    def setupUi(self, CoffeeApp):
        CoffeeApp.setObjectName("CoffeeApp")
        CoffeeApp.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=CoffeeApp)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.refreshButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.refreshButton.setMinimumHeight(30)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout.addWidget(self.refreshButton)
        self.addButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addButton.setMinimumHeight(30)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.editButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.editButton.setMinimumHeight(30)
        self.editButton.setObjectName("editButton")
        self.horizontalLayout.addWidget(self.editButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.coffeeTable = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.coffeeTable.setColumnCount(7)
        self.coffeeTable.setRowCount(0)
        self.coffeeTable.setHorizontalHeaderLabels(['ID', 'Название', 'Степень обжарки', 'Форма', 'Описание вкуса', 'Цена', 'Объём упаковки'])
        self.coffeeTable.setObjectName("coffeeTable")
        item = QtWidgets.QTableWidgetItem()
        self.coffeeTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.coffeeTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.coffeeTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.coffeeTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.coffeeTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.coffeeTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.coffeeTable.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.coffeeTable)
        CoffeeApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=CoffeeApp)
        self.menubar.setObjectName("menubar")
        CoffeeApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=CoffeeApp)
        self.statusbar.setObjectName("statusbar")
        CoffeeApp.setStatusBar(self.statusbar)

        self.retranslateUi(CoffeeApp)
        QtCore.QMetaObject.connectSlotsByName(CoffeeApp)

    def retranslateUi(self, CoffeeApp):
        _translate = QtCore.QCoreApplication.translate
        CoffeeApp.setWindowTitle(_translate("CoffeeApp", "Информация о кофе"))
        self.refreshButton.setText(_translate("CoffeeApp", "Обновить данные"))
        self.addButton.setText(_translate("CoffeeApp", "Добавить"))
        self.editButton.setText(_translate("CoffeeApp", "Редактировать"))
        item = self.coffeeTable.horizontalHeaderItem(0)
        item.setText(_translate("CoffeeApp", "ID"))
        item = self.coffeeTable.horizontalHeaderItem(1)
        item.setText(_translate("CoffeeApp", "Название"))
        item = self.coffeeTable.horizontalHeaderItem(2)
        item.setText(_translate("CoffeeApp", "Степень обжарки"))
        item = self.coffeeTable.horizontalHeaderItem(3)
        item.setText(_translate("CoffeeApp", "Форма"))
        item = self.coffeeTable.horizontalHeaderItem(4)
        item.setText(_translate("CoffeeApp", "Описание вкуса"))
        item = self.coffeeTable.horizontalHeaderItem(5)
        item.setText(_translate("CoffeeApp", "Цена"))
        item = self.coffeeTable.horizontalHeaderItem(6)
        item.setText(_translate("CoffeeApp", "Объём упаковки"))
